name: Build and Evaluate Model

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run model script
      run: python model.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          best_model.pkl
          *.png
